services:
  esp-idf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: espidf-build-env
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspaces:cached
    working_dir: /workspaces
    devices:
      # - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0

    # socat で仮想シリアルを作るために必要
    # cap_add:
    #   - SYS_ADMIN

    # command: >
    #   bash -c "
    #   apt-get update &&
    #   apt-get install -y socat &&
    #   socat
    #       PTY,link=/dev/ttyM5,raw,echo=0,mode=666
    #       TCP:host.docker.internal:2000 &
    #   exec bash
    #   "